"""工具协议：让 developer / tester 这类 Pod 能真正行动，而不只生成文本。

协议（系统的「手」）：模型在其产出中以一个 fenced 块声明要执行的动作，
Pod 解析后在沙箱内按序执行，并把结果回填给模型做收尾。格式：

    ```actions
    [
      {"action": "write_file", "path": "solution.py", "content": "..."},
      {"action": "run", "cmd": ["python", "solution.py"], "timeout": 30}
    ]
    ```

支持动作：write_file / read_file / list_dir / run。
Mock 模式下，developer/tester 由 mock_actions() 给出确定性的真实动作（真的写文件、真的跑命令），
以此在零密钥环境下也能证明沙箱能力可用。
"""
import json
import re

from .sandbox import Sandbox

ACTION_FENCE = re.compile(r"```actions\s*(.*?)```", re.DOTALL | re.IGNORECASE)

TOOL_INSTRUCTIONS = """\
# 你拥有沙箱执行工具（真实读写文件、跑命令）

当本阶段需要产出可运行代码或执行测试时，请在回复中包含如下 fenced 块，
系统会在沙箱内按序执行，并把结果回填给你做收尾总结：

```actions
[
  {"action": "write_file", "path": "solution.py", "content": "<代码文本>"},
  {"action": "run", "cmd": ["python", "solution.py"], "timeout": 30}
]
```

动作清单：
- write_file: {"path": "相对沙箱的路径", "content": "文件全文"}
- read_file:  {"path": "..."}
- list_dir:   {"path": "."}
- run:        {"cmd": ["可执行文件(白名单)", "参数..."], "timeout": 30}

约束：路径相对于沙箱根，禁止越界；命令仅限白名单（python/node/pytest/git 等）。"""


def parse_actions(text: str):
    """从模型产出中提取动作列表；无则返 []。"""
    m = ACTION_FENCE.search(text)
    if not m:
        return []
    try:
        data = json.loads(m.group(1).strip())
    except json.JSONDecodeError:
        return []
    return data if isinstance(data, list) else []


def execute_actions(sandbox: Sandbox, actions: list) -> list:
    """在沙箱内执行动作，返回结果列表（每项含 action/ok/detail）。"""
    results = []
    for i, act in enumerate(actions):
        if not isinstance(act, dict):
            results.append({"action": "?", "ok": False, "detail": "动作格式错误"})
            continue
        kind = act.get("action")
        try:
            if kind == "write_file":
                detail = sandbox.write_file(act["path"], act.get("content", ""))
                results.append({"action": "write_file", "path": act["path"], "ok": True, "detail": detail})
            elif kind == "read_file":
                detail = sandbox.read_file(act["path"])
                results.append({"action": "read_file", "path": act["path"], "ok": True, "detail": detail})
            elif kind == "list_dir":
                detail = sandbox.list_dir(act.get("path", "."))
                results.append({"action": "list_dir", "path": act.get("path", "."), "ok": True, "detail": detail})
            elif kind == "run":
                res = sandbox.run(act.get("cmd", []), int(act.get("timeout", 60)))
                results.append({"action": "run", "cmd": act.get("cmd"), "ok": res["rc"] == 0, "detail": res})
            else:
                results.append({"action": kind, "ok": False, "detail": f"未知动作: {kind}"})
        except Exception as e:  # 沙箱边界/IO 异常都转为结构化结果，不中断编排
            results.append({"action": kind, "ok": False, "detail": f"{type(e).__name__}: {e}"})
    return results


def format_results(results: list) -> str:
    lines = ["## 沙箱执行记录", ""]
    for i, r in enumerate(results):
        status = "OK " if r["ok"] else "ERR"
        head = f"- [{status}] {i+1}. {r['action']}"
        if "path" in r:
            head += f" → {r['path']}"
        if "cmd" in r:
            head += f" → {' '.join(r['cmd'])}"
        lines.append(head)
        d = r["detail"]
        if isinstance(d, dict):  # run 的结果
            lines.append(f"    rc={d.get('rc')}")
            if d.get("stdout"):
                lines.append("    stdout:")
                lines.append(_indent(d["stdout"]))
            if d.get("stderr"):
                lines.append("    stderr:")
                lines.append(_indent(d["stderr"]))
        else:
            lines.append(_indent(str(d)))
    return "\n".join(lines)


def _indent(s: str, n: int = 4) -> str:
    return "\n".join((" " * n) + ln for ln in s.splitlines())


def mock_actions(role: str, requirement: str) -> list:
    """Mock 模式下 developer/tester 的确定性真实动作（沙箱内真写真跑）。"""
    req_line = requirement.strip().replace("\n", " ")
    if role == "developer":
        code = (
            f"# Auto-generated by developer pod (MOCK)\n"
            f"# Requirement: {req_line}\n"
            f"def run():\n"
            f"    return \"implemented: {req_line[:60]}\"\n\n"
            f"if __name__ == \"__main__\":\n"
            f"    print(\"run() ->\", run())\n"
        )
        return [
            {"action": "write_file", "path": "solution.py", "content": code},
            {"action": "run", "cmd": ["python", "solution.py"], "timeout": 30},
        ]
    if role == "tester":
        test = (
            "import solution\n"
            "assert solution.run(), 'run() 不应为空'\n"
            "print('TEST PASS')\n"
        )
        return [
            {"action": "write_file", "path": "_test_solution.py", "content": test},
            {"action": "run", "cmd": ["python", "_test_solution.py"], "timeout": 30},
        ]
    return []
